# WaveAlert360 is a mission-driven project seeking pilot funding and expertise
# to install a real-world coastal safety system at Cowell Ranch State Beach

custom: ['mailto:prasannapadmanabhan@gmail.com?subject=WaveAlert360%20Support', 'https://github.com/prasannapad/wavealert360#-help-take-this-from-prototype-to-real-world-pilot']
